backend:
  image:
    repository: devops2526/yas-search
    digest: sha256:47e54732261585da7f47089ced6105f775aafc0abbead1647de86ff90fa3969f
    tag: latest
  serviceMonitor:
    enabled: false

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
