backend:
  image:
    repository: devops2526/yas-search
    digest: sha256:7a013f81583708992706ca1173f72ed4d49e961461ac75b3eaac8750d9843eb1
    tag: latest
  serviceMonitor:
    enabled: false

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
