backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-search
    digest: sha256:3d8eaf0f31c7b830a12de8ed536779600c5e4b2dc41416978e87b6a8844eb66b
    tag: latest
  serviceMonitor:
    enabled: false

  nameOverride: search
  fullnameOverride: search
  databaseName: search
  ingress:
    enabled: false
  extraEnvFroms:
    - secretRef:
        name: yas-elasticsearch-credentials-secret
  extraVolumes:
    - name: search-application
      configMap:
        name: search-application-configmap
  extraVolumeMounts:
    - name: search-application
      mountPath: /opt/yas/search
  extraApplicationConfigPaths:
    - /opt/yas/search/search-application.yaml
