apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backoffice-bff-dev
  namespace: argocd
spec:
  project: yas-dev
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/backoffice-bff
    helm:
      releaseName: backoffice-bff
      values: |
        backend:
          image:
            digest: "sha256:2e6f8886de6e618dff070f8c6403f393e05775ceb0bec6d5f542fe0471413d57"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
