apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-dev
  namespace: argocd
spec:
  project: yas-dev
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/media
    helm:
      releaseName: media
      values: |
        backend:
          image:
            digest: "sha256:36c9997f44737e515663cb7d69010505cfbd9331d8d020733579d234e4e0f630"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
