apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-dev
  namespace: argocd
spec:
  project: yas-dev
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/order
    helm:
      releaseName: order
      values: |
        backend:
          image:
            digest: "sha256:51b83c4abe42f9bccd6926112a78b1e7edfa8b145d95afc3f7925fda46eefc85"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
