apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-dev
  namespace: argocd
spec:
  project: yas-dev
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/order
    helm:
      releaseName: order
      valueFiles:
        - values.yaml
        - ../values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
