apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-bff-dev
  namespace: argocd
spec:
  project: yas-dev
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/storefront-bff
    helm:
      releaseName: storefront-bff
      values: |
        backend:
          image:
            digest: "sha256:b320e530e5daf04a13497c3ca7fe759e6561efbfae19044d3fb240fd67b137de"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
