# Shared overrides for dev testing.
# Apply together with each chart's base values.yaml.

backend:
  image:
    tag: "dev-fixed"
  serviceMonitor:
    enabled: false

ui:
  image:
    tag: "dev-fixed"
  service:
    type: NodePort

sampledata:
  image:
    tag: "16.3-alpine"
  serviceMonitor:
    enabled: false
