apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-staging
  namespace: argocd
spec:
  project: yas-staging
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/search
    helm:
      releaseName: search
      values: |
        backend:
          image:
            digest: "sha256:3d8eaf0f31c7b830a12de8ed536779600c5e4b2dc41416978e87b6a8844eb66b"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
