apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: search-staging
  namespace: argocd
spec:
  project: yas-staging
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/search
    helm:
      releaseName: search
      values: |
        backend:
          image:
            digest: "sha256:7a013f81583708992706ca1173f72ed4d49e961461ac75b3eaac8750d9843eb1"
          serviceMonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
