apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront-ui-staging
  namespace: argocd
spec:
  project: yas-staging
  source:
    repoURL: https://github.com/Intro-to-DevOps-25-26/yas.git
    targetRevision: main
    path: k8s/charts/storefront-ui
    helm:
      releaseName: storefront-ui
      values: |
        ui:
          image:
            digest: "sha256:dce545b45342adbcdfc0e7bfa3131a87ccb967a7ae02885e0009950a2324a3ae"
          service:
            type: NodePort
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false
