sampledata:
  image:
    repository: postgres
    tag: "16.3-alpine"
    pullPolicy: IfNotPresent
    digest: ""

  nameOverride: sampledata
  fullnameOverride: sampledata

  job:
    backoffLimit: 1
    ttlSecondsAfterFinished: 300

  database:
    host: postgresql.postgres.svc.cluster.local
    port: 5432
    usernameSecret: yas-postgresql-credentials-secret
    productName: product
    mediaName: media

  scripts:
    product: product.sql
    media: media.sql

  resources: {}

  podSecurityContext: {}
  securityContext: {}

serviceAccount:
  create: false
  name: ""
