backend:
  image:
    repository: ghcr.io/nashtech-garage/yas-tax
    tag: latest
  serviceMonitor:
    enabled: false

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
